// generated by build-site.mjs — 編集しない
const V = "sokuho-c58e1e5b";
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (e) => e.waitUntil(
  caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== V).map((k) => caches.delete(k)))).then(() => self.clients.claim())
));
self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    fetch(req).then((res) => caches.open(V).then((c) => { c.put(req, res.clone()); return res; }))
      .catch(() => caches.match(req))
  );
});
